### ISSUE TITLE
Extend search (outside of Austin)

### ISSUE THREAD

**Issue by amberleyromo** [travel-consensus/cinemaplate#18]
General functionality implemented. 

When a zip code is entered that isn't in the database already, it makes the request to Yelp for restaurants with Eat24 status in that area -- populates the database with those restaurants.

Bug: The first time you ask for restaurants from a new zip code, it doesn't work. The next time, it'll work.

**Comment by JonKrone** [comment]
Moved from done to in-progress because code had not been merged. Will re-pull, merge and then test before submitting a PR.

**Comment by JonKrone** [comment]
blocker: The branch was about 30 commits behind and I'm not sure of code quality after resolving 7 or 8 conflicts. Testing but may need time.
