### ISSUE TITLE
Bug loading restaurants from a new zipcode

### ISSUE THREAD

**Issue by amberleyromo** [travel-consensus/cinemaplate#19]
Ref #18.

**Comment by JonKrone** [comment]
bug: The first time a user spins the roulette for a zipcode that does not appear in the database, restaurant options do not populate.

**Comment by amberleyromo** [comment]
From Jon(channel): This is a server-side problem where the new zip code's restaurants haven't loaded before the response is sent. I'll implement the missing wait-on-new-zipcode feature tomorrow, just requires a little callback managing.

**Comment by dotkam** [comment]
In index.js:
not in use / test -- routes.get('/api/match/restaurant/:zip'...
production -- routes.get('/api/match/:zip'...
