### ISSUE TITLE
Database attempts to insert movies twice.

### ISSUE THREAD

**Issue by JonKrone** [travel-consensus/cinemaplate#46]

**Comment by prozack** [comment]
Not a bug.  Appears Reddit API returns multiple instances of a movie when called.  Any redundancy is taken care of by unique title field in database as opposed to filtering at an earlier point. This is where the duplicate entries and error messages are generated from.  

In addition attempts to modify the Reddit link to scrape more movies were unsuccessful and produced errors when seeding database.
