### ISSUE TITLE
Display eat24 menu in modal

### ISSUE THREAD

**Issue by amberleyromo** [travel-consensus/cinemaplate#5]
Rather than an outbound link.

![screen shot 2016-02-24 at 11 12 37 am](https://cloud.githubusercontent.com/assets/3461087/13294031/bb8305b2-dae7-11e5-8a5f-807b25c89767.png)

**Comment by ghost** [comment]
There is an issue with the spinner not displaying whenever the link is clicked and processing

**Comment by amberleyromo** [comment]
Modal functional. Breaking out spinner issue to #14.
